// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GetJsonPathFromCursor
{
    internal sealed partial class Vsix
    {
        public const string Id = "GetJsonPathFromCursor.ddf5199e-94cf-4ebd-b609-3fcd3359fda6";
        public const string Name = "Get Json Path From Cursor";
        public const string Description = @"Get Json Path From Cursor";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "CodingSeb";
        public const string Tags = "";
    }
}
