// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GetJsonPathFromCursor
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GetJsonPathFromCursorString = "d275998e-5f95-4f3a-ae5a-b5878a529d3e";
        public static Guid GetJsonPathFromCursor = new Guid(GetJsonPathFromCursorString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int GetJsonPathCommand = 0x0100;
    }
}